version: 0.2
phases:
  pre_build:
    commands:
      # Loggin in to Dockerhub
      - echo $dockerpass | docker login --username $dockeruser --password-stdin
      # Logging in to ECR
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s5o7d0z2
      - REPOSITORY_URI=public.ecr.aws/s5o7d0z2/vishal-demo-repo
  build:
    commands:
      - docker build . -t $REPOSITORY_URI:mywebapp
      - docker build -f Dockerfile-mysql . -t $REPOSITORY_URI:mydb 
  post_build:
    commands:
      # Check if the build stage is successful
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Build completed on `date`
      # Pushing the image to ECR
      - docker push $REPOSITORY_URI:mywebapp
      - docker push $REPOSITORY_URI:mydb
artifacts:
  files:
    - 'imagedefinitions.json'
  name: artifacts  
